name: Development CD

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.set-node-version.outputs.NODE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read engine versions
        id: set-node-version
        run: |
          echo "NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false

      - name: Install Node.js ${{ steps.set-node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.set-node-version.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Check types
        run: |
          pnpm lint:types

      - name: Lint
        run: |
          pnpm lint

      - name: Test
        run: |
          pnpm test

      - name: Build
        run: |
          pnpm build:code
          pnpm build:types
